Import libraries, Encoder, Preprocessing and Model

In [1]:
import seaborn as sns
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

Load dataset

In [2]:
# load the data
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:

# # make the X and y 
# X = df[['size','sex','day','time']]
# y = df['total_bill']

Call the Linear Model and Encode the data from categorical to numeric form

In [9]:
# call the models
model = LinearRegression()

# encode the sex,day,time
columns = ['sex','time','day']
encoder_columns = {}
for col in columns:
    encode = LabelEncoder()
    df[col] = encode.fit_transform(df[col])
    encoder_columns[col] = encode

Make Features and Labels

In [10]:
# make the X and y 
X = df[['size','sex','day','time']]
y = df['total_bill']

Fit the model

In [12]:
predict = model.fit(X,y)
df.head()

   total_bill   tip  sex smoker  day  time  size
0       16.99  1.01    0     No    2     0     2
1       10.34  1.66    1     No    2     0     3
2       21.01  3.50    1     No    2     0     3
3       23.68  3.31    1     No    2     0     2
4       24.59  3.61    0     No    2     0     4

Check the Coefficient and intercept

In [18]:
# now check the coffients in multiple linear regression
print("Coefficients : ",predict.coef_)

# now check the intercept of the multiple linear Regression
print("Intercept : ",predict.intercept_)

Coefficients :  [ 5.45728296  1.36058426 -0.15509435 -1.93134854]
Intercept :  5.695445304457069

Predict the totall bill

In [19]:

# now predict the total bill 

print("Prediction of the total bill after : ",predict.predict([[4,1,2,0]]))

Prediction of the total bill after :  [28.57497271]

c:\Users\Abu bakar\anaconda3\envs\python_ml\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Inverse the encoded data

In [ ]:
# inverse the encoded columns
for col in columns:
    le = encoder_columns[col]
    df[col] = le.inverse_transform(df[col].astype(int))

In [7]:
print(encoder_columns)

{'sex': LabelEncoder(), 'time': LabelEncoder(), 'day': LabelEncoder()}

In [8]:
for col in columns:
    print(col, encoder_columns[col].classes_)

sex ['Female' 'Male']
time ['Dinner' 'Lunch']
day ['Fri' 'Sat' 'Sun' 'Thur']