Import libraries, Encoder, Preprocessing and Model

In [2]:

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

Load dataset

In [3]:
# load the data
df = pd.read_csv("House Price Prediction Dataset.csv")
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [4]:
df.isnull().sum().sort_values(ascending = True)

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

Call the Linear Model and Encode the data from categorical to numeric form

In [5]:
# call the models
model = LinearRegression()

columns_to_encod = ['Location','Condition','Garage']
encoded_columns= {}
for col in columns_to_encod:
    label = LabelEncoder()
    df[col] = label.fit_transform(df[col])
    encoded_columns[col] = label
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,0,0,0,149919
1,2,4272,5,4,3,1958,0,0,0,424998
2,3,3592,2,2,3,1938,0,2,0,266746
3,4,966,4,2,2,1902,2,1,1,244020
4,5,4926,1,4,2,1975,0,1,1,636056

Make Features and Labels

In [6]:
# make the X and y 
X = df.drop(['Price','Area','Id'],axis=1)
y = df.Price

Fit the model

In [7]:
predict = model.fit(X,y)
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,0,0,0,149919
1,2,4272,5,4,3,1958,0,0,0,424998
2,3,3592,2,2,3,1938,0,2,0,266746
3,4,966,4,2,2,1902,2,1,1,244020
4,5,4926,1,4,2,1975,0,1,1,636056

Check the Coefficient and intercept

In [8]:
# now check the coffients in multiple linear regression
print("Coefficients : ",predict.coef_)

# now check the intercept of the multiple linear Regression
print("Intercept : ",predict.intercept_)

Coefficients :  [ -721.88174479 -4320.35190664 19436.19701173    39.23157773
 -2992.43215522 -3876.67996022  2182.95796318]
Intercept :  444202.8275644242

In [9]:
X.columns

Index(['Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt', 'Location', 'Condition',
       'Garage'],
      dtype='object')

Predict the totall price of house

In [10]:

# now predict the total price of house 

import numpy as np
new_data = np.array([[5, 4, 2, 2020, 1, 0, 1]])
pred = model.predict(new_data)
# or
# pred = model.predict([[5, 4, 2, 2020, 1, 0, 1]])
print("Prediction of the total price of the house is : ",pred)

Prediction of the total price of the house is :  [540622.71806829]

c:\Users\Abu bakar\anaconda3\envs\python_ml\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Inverse the encoded data

In [11]:
# inverse the encoded columns

for col in columns_to_encod:
    en = encoded_columns[col]
    df[col] = en.inverse_transform(df[col])

In [12]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056