Import libraries Label Encoder for preprocessing

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

read the employee csv file

In [4]:
df=pd.read_csv("All CSV files/employee.csv")
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

Label Encoding by using the Technique of "LABEL ENCODER"

In [5]:
le = LabelEncoder()
df['eb']=le.fit_transform(df['EverBenched'])
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,eb
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,0
4,Masters,2017,Pune,3,24,Male,Yes,2,1,1

Feature Encoding by using the Technique of "ORDER" (feature having ordinal Categories)

In [6]:
education_encoder = {'Bachelors':0,'Masters':1,'phD':2}
df['edu_encoder'] = df["Education"].map(education_encoder)
df['edu_encoder'].head()

0    0.0
1    0.0
2    0.0
3    1.0
4    1.0
Name: edu_encoder, dtype: float64

ONE-HOT Encoding

In [7]:
df = pd.get_dummies(df,columns = ['City'],prefix = "City")
df.head()

,Education,JoiningYear,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,eb,edu_encoder,City_Bangalore,City_New Delhi,City_Pune
0,Bachelors,2017,3,34,Male,No,0,0,0,0.0,True,False,False
1,Bachelors,2013,1,28,Female,No,3,1,0,0.0,False,False,True
2,Bachelors,2014,3,38,Female,No,2,0,0,0.0,False,True,False
3,Masters,2016,3,27,Male,No,5,1,0,1.0,True,False,False
4,Masters,2017,3,24,Male,Yes,2,1,1,1.0,False,False,True

Frequency Encoding

In [8]:
education_counts = df['Education'].value_counts().to_dict()
df['frequency_encoding'] = df["Education"].map(education_counts)
df.head()

,Education,JoiningYear,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,eb,edu_encoder,City_Bangalore,City_New Delhi,City_Pune,frequency_encoding
0,Bachelors,2017,3,34,Male,No,0,0,0,0.0,True,False,False,3601
1,Bachelors,2013,1,28,Female,No,3,1,0,0.0,False,False,True,3601
2,Bachelors,2014,3,38,Female,No,2,0,0,0.0,False,True,False,3601
3,Masters,2016,3,27,Male,No,5,1,0,1.0,True,False,False,873
4,Masters,2017,3,24,Male,Yes,2,1,1,1.0,False,False,True,873

Target Encoding

In [9]:
target_encoding = df.groupby('Gender')["eb"].mean().to_dict()
df["targrt_encoding"] = df["Education"].map(target_encoding)
df

,Education,JoiningYear,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,eb,edu_encoder,City_Bangalore,City_New Delhi,City_Pune,frequency_encoding,targrt_encoding
0,Bachelors,2017,3,34,Male,No,0,0,0,0.0,True,False,False,3601,NaN
1,Bachelors,2013,1,28,Female,No,3,1,0,0.0,False,False,True,3601,NaN
2,Bachelors,2014,3,38,Female,No,2,0,0,0.0,False,True,False,3601,NaN
3,Masters,2016,3,27,Male,No,5,1,0,1.0,True,False,False,873,NaN
4,Masters,2017,3,24,Male,Yes,2,1,1,1.0,False,False,True,873,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,3,26,Female,No,4,0,0,0.0,True,False,False,3601,NaN
4649,Masters,2013,2,37,Male,No,2,1,0,1.0,False,False,True,873,NaN
4650,Masters,2018,3,27,Male,No,5,1,0,1.0,False,True,False,873,NaN
4651,Bachelors,2012,3,30,Male,Yes,2,0,1,0.0,True,False,False,3601,NaN
4652,Bachelors,2015,3,33,Male,Yes,4,0,1,0.0,True,False,False,3601,NaN