import Libraries and scalar  techniques

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler, MinMaxScaler

read the csv file

In [2]:
df = pd.read_csv('All CSV files/employee.csv')
print(df.columns)

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [7]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

call and fit+transform stander scalar model

In [8]:
stds = StandardScaler()
df['std_scaler'] = stds.fit_transform(df[['JoiningYear']])
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,std_scaler
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,1.039638
1,Bachelors,2013,Pune,1,28,Female,No,3,1,-1.107233
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,-0.570515
3,Masters,2016,Bangalore,3,27,Male,No,5,1,0.502921
4,Masters,2017,Pune,3,24,Male,Yes,2,1,1.039638

call and fit_transform MinMax scalar model

In [9]:
min_max_scaler = MinMaxScaler()
df['min_max_scaler'] = min_max_scaler.fit_transform(df[['JoiningYear']])

In [10]:
df[['min_max_scaler','std_scaler']].head()

   min_max_scaler  std_scaler
0        0.833333    1.039638
1        0.166667   -1.107233
2        0.333333   -0.570515
3        0.666667    0.502921
4        0.833333    1.039638

Import the MaxAbsScalar

In [11]:
from sklearn.preprocessing import MaxAbsScaler

call and fit_transform MaxAbs scalar model

In [12]:
max_abs_scaler = MaxAbsScaler()
df['max_abs_scaler'] = max_abs_scaler.fit_transform(df[['JoiningYear']])
df[['max_abs_scaler']].head()

   max_abs_scaler
0        0.999504
1        0.997522
2        0.998018
3        0.999009
4        0.999504

In [13]:
df[['std_scaler','min_max_scaler','max_abs_scaler']].head()

   std_scaler  min_max_scaler  max_abs_scaler
0    1.039638        0.833333        0.999504
1   -1.107233        0.166667        0.997522
2   -0.570515        0.333333        0.998018
3    0.502921        0.666667        0.999009
4    1.039638        0.833333        0.999504