Advance Techniques

2. Multiple imputation by chained Equations(MICE)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
# itrative imputer is to impute all the null values together rather then individually
from sklearn.experimental import enable_iterative_imputer
# itrative imputer is just an experimental, it might be give the wrong value because it is in beta version means under improving 
from  sklearn.impute import IterativeImputer
# first point is enable the itrative imputer first then import the IterativeImputer without enable the ItrativeImputer will not import or not work
df = sns.load_dataset('titanic')
df.head()

# missing_values = df.isnull().sum().sort_values(ascending=False)
# print(missing_values)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
# check the missing,null,nan values from the data
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

Enode the data into  0,1,2

In [8]:
# LabelEncoder is used to convert the catagrical values into numeric in the form of 0 1 2 0 1 2 0 1 2 
from sklearn.preprocessing import LabelEncoder
# mention the columns the to encode 
columns_to_encode = ['sex','embarked','who','deck','class','embark_town','alive']
# Dictionary to store labelEncoders for each column
label_encoders = {}
# Loop to apply LabelEncoder to impute each column 
for col in columns_to_encode:
    # call the LabelEncoder and store in an object
    le = LabelEncoder()
    # train the model and tranform
    df[col] = le.fit_transform(df[col])
    # store the encoder into the label_encoders dictionary
    label_encoders[col] = le
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,7,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,2,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,7,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,7,2,0,True

encode the data without loop

In [5]:
# # impute the one single column without the loop 
# from sklearn.preprocessing import LabelEncoder
# columns_to_encode = ['sex','embarked','who','deck','class','embark_town','alive']
# encoder = LabelEncoder()
# df['sex']= encoder.fit_transform(df['sex'])
# df['embarked']= encoder.fit_transform(df['embarked'])
# df['who']= encoder.fit_transform(df['who'])
# df['deck']= encoder.fit_transform(df['deck'])
# df['lass']= encoder.fit_transform(df['class'])
# df['embark_town']= encoder.fit_transform(df['embark_town'])
# df['alive']= encoder.fit_transform(df['alive'])

impute the missing values by using the IterativeImputer

In [9]:
# impute the missing values by using the IterativeImputer
# call the IterativeImputer class with max_iteratiion = 10
# means it will run 10 time for checking and then calculate the average and then impute on the missing_values
imputer = IterativeImputer(max_iter=10)

# impute the missing values using the IterativeImputer in a for loop for age, embark_town, embarked and deck columns
# columns to impute 
column_to_impute = ['age','embarked','embark_town','deck']

# Loop to impute each column
for col in column_to_impute:
    df[col] = imputer.fit_transform(df[[col]])

# ceck the missing missing_values
df.isnull().sum().sort_values(ascending = False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

Inverse the Encoded data by using the inverse_transform into same as orignal form

In [6]:
# inverse the transform for encoded columns 
for col in columns_to_encode:
    # Retrieve the corresponding LabelEncoder for  the column 
    le = label_encoders[col]
    # Inverse transform the data and convert to integer type
    df[col] = le.inverse_transform(df[col].astype(int))

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True